app:
  env: "development"
  port: 8080
  context_path: "/class-room-price-mapping-processor-schedule"
  host: "localhost"
  root_path: "/api"
  version: 1.0
database:
  host: localhost
  name: unisunauthdb
  user: urquhmotrdhwqg
  pass: efad4bb2169e67ddaa17c21aba5c76efc6a9daa6a06310949eba9a006bf258da
  port: 5432
  ssl: disable
  timezone: Asia/Bangkok
endpoint:
  strapi-information-gateway:
    host: "http://localhost:8080"
    path: "/strapi-information-gateway/api/v1/strapi"
  class_room:
    path: /api/class-rooms
    query: ?fields[0]=id&fields[1]=prices
  promotion:
    path: /api/promotions
    query: ?populate=*
GIN_MODE: "debug"
